apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-bot
  labels:
    app.kubernetes.io/name: vote-bot
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-bot
  template:
    metadata:
      labels:
        app: vote-bot
    spec:
      containers:
      - command:
        - emojivoto-vote-bot
        env:
        - name: WEB_HOST
          value: web-svc:80
        - name: RATE_IN_MILLIS
          value: "1000"
        image: ljanatka/emojivoto-web:v1
        name: vote-bot
        resources:
          requests:
            cpu: 10m
